// api/create-pr.js
export default async function handler(req, res) {
    // Only allow POST requests
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    const { x, y, color, githubUsername } = req.body;

    if (!x || !y || !color || !githubUsername) {
        return res.status(400).json({ error: 'Missing required fields' });
    }

    const token = process.env.GITHUB_TOKEN;
    if (!token) {
        console.error('GITHUB_TOKEN is not set in environment variables');
        return res.status(500).json({ error: 'Server configuration error' });
    }

    const owner = 'homayounmmdy';
    const repo = 'billion-grid';
    const branchName = `claim/${githubUsername}-${Date.now()}`;
    const filePath = 'public/grid-data.json';
    const timestamp = new Date().toISOString();
    const newSquare = { x, y, userId: githubUsername, color, timestamp };

    try {
        // 1. Fetch the current file content and its SHA
        let currentContent = '[]';
        let fileSha = '';

        try {
            const fileRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${filePath}?ref=main`, {
                headers: {
                    'Authorization': `token ${token}`,
                    'Accept': 'application/vnd.github.v3+json'
                }
            });

            if (fileRes.ok) {
                const fileData = await fileRes.json();
                fileSha = fileData.sha;
                currentContent = Buffer.from(fileData.content, 'base64').toString('utf-8');
            }
        } catch (err) {
            // File might not exist yet, which is fine. We'll start with an empty array.
            console.log('File does not exist yet, starting fresh.');
        }

        // 2. Parse, append, and re-encode the content
        let gridData = [];
        try {
            gridData = JSON.parse(currentContent);
        } catch (e) {
            gridData = [];
        }

        gridData.push(newSquare);
        const newContentBase64 = Buffer.from(JSON.stringify(gridData, null, 2)).toString('base64');

        // 3. Create the new file (this automatically creates the new branch)
        const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`, {
            method: 'PUT',
            headers: {
                'Authorization': `token ${token}`,
                'Accept': 'application/vnd.github.v3+json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                message: `chore: add square claim by @${githubUsername}`,
                content: newContentBase64,
                sha: fileSha || undefined, // Required if file exists
                branch: branchName
            })
        });

        if (!commitRes.ok) {
            const errData = await commitRes.json();
            console.error('GitHub API Commit Error:', errData);
            return res.status(500).json({ error: 'Failed to create commit on GitHub' });
        }

        // 4. Create the Pull Request
        const prTitle = `🎯 Claim: Square (${x.toLocaleString()}, ${y.toLocaleString()}) by @${githubUsername}`;
        const prBody = `## 🎯 New Square Claim

**User:** @${githubUsername}  
**Coordinates:** (\`${x.toLocaleString()}\`, \`${y.toLocaleString()}\`)  
**Color:** \`${color}\`  
**Timestamp:** \`${timestamp}\`

---
*This PR was automatically generated by the [Billion Grid App](https://billion-grid.vercel.app/).*  
*The GitHub Actions workflow will automatically validate that only one square was added.*`;

        const prRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
            method: 'POST',
            headers: {
                'Authorization': `token ${token}`,
                'Accept': 'application/vnd.github.v3+json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                title: prTitle,
                head: branchName,
                base: 'main',
                body: prBody
            })
        });

        if (!prRes.ok) {
            const errData = await prRes.json();
            console.error('GitHub API PR Error:', errData);
            return res.status(500).json({ error: 'Failed to create Pull Request' });
        }

        const prData = await prRes.json();

        // 5. Success! Return the PR URL to the frontend
        return res.status(200).json({
            success: true,
            prUrl: prData.html_url,
            message: 'Pull Request created successfully!'
        });

    } catch (error) {
        console.error('Server Error:', error);
        return res.status(500).json({ error: 'Internal server error' });
    }
}
